[General]
NotificationX=915
NotificationY=140

;Pausa entre o convite de uma mula e a próxima.
InviteDelay=180
;Pausa depois de enviar todos os convites e antes de começar os aceites.
BeforeAcceptDelay=50
;Pausa entre o aceite de uma mula e a próxima.
AcceptDelay=100

; Botao expulsar da PT
KickX=1685
KickY=700

; Botao de transferir lider
TransferLeaderX=1765
TransferLeaderY=701

; Botao de sair da PT
LeavePartyX=1765
LeavePartyY=730

; Tempo entre selecionar a mula e clicar no botão da ação.
PartySelectDelay=100
; Tempo depois de clicar em Expulsar.
PartyKickDelay=50
; Tempo depois de clicar em Transferir liderança.
PartyTransferDelay=300
; Espera adicional antes de clicar em Sair da PT.
PartyBeforeLeaveDelay=200
; Tempo depois de clicar em Sair da PT.
PartyLeaveDelay=300

[Mule1]
Name=Mula 1
FriendX=70
FriendY=648
InviteX=100
InviteY=675
PartyX=1670
PartyY=488

[Mule2]
Name=Mula 2
FriendX=70
FriendY=668
InviteX=100
InviteY=692
PartyX=1670
PartyY=505

[Mule3]
Name=Mula 3
FriendX=70
FriendY=686
InviteX=100
InviteY=710
PartyX=1670
PartyY=523

[Mule4]
Name=Mula 4
FriendX=70
FriendY=705
InviteX=100
InviteY=732
PartyX=1670
PartyY=540

[Mule5]
Name=Mula 5
FriendX=70
FriendY=723
InviteX=100
InviteY=747
PartyX=1670
PartyY=557

[Mule6]
Name=Mula 6
FriendX=70
FriendY=743
InviteX=100
InviteY=767
PartyX=1670
PartyY=573

[Mule7]
Name=Mula 7
FriendX=70
FriendY=764
InviteX=100
InviteY=789
PartyX=1670
PartyY=591

[Mule8]
Name=Mula 8
FriendX=70
FriendY=782
InviteX=100
InviteY=805
PartyX=1670
PartyY=609

[Mule9]
Name=Mula 9
FriendX=70
FriendY=800
InviteX=100
InviteY=806
PartyX=1670
PartyY=625
